---
- hosts: Prod1:Prod2
  vars:
    ansible_site_path: "c:\\inetpub\\wwwroot\\{{site_path}}"

  tasks:
  - name: latest fetch from artifact
    win_get_url:
      url: URL of Latest artifact from nexus
      dest: D:\{{site_path}}.zip

  - name: stop site
    win_iis_website:
      name: "{{site_path}}"
      state: stopped

  - name: restart IIS
    win_service:
      name: IISADMIN
      state: restarted 

  - name: delete directory
    win_file:
      path: C:\inetpub\wwwroot\{{site_path}}
      state: absent

  - name: create directory
    win_file:
      path: C:\inetpub\wwwroot\{{site_path}}
      state: directory

  - name: unzip
    win_unzip:
      src: D:\{{site_path}}.zip
      dest: C:\inetpub\wwwroot\{{site_path}}\

  - name: restart site
    win_iis_website:
      name: "{{site_name}}"
      state: restarted
      physical_path: "{{ ansible_site_path }}"
     
